name: CI/CD api-ecommerce

env:
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: api-ecommerce

on:
  push:
    branches:
      - main

jobs:

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js (if you're using Node.js for testing)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or any version you're using

      - name: Install dependencies
        run: npm install  # Or any other dependency manager you're using

      - name: Run unit tests
        run: npm test  # Or your specific test command, e.g., "pytest" for Python

  build-and-push-job:
    runs-on: ubuntu-latest
    needs: test-job  # This ensures the build job will only run if the test job is successful
    steps:

      - name: Clone Source Code 
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image with specific version
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
      
      - name: Push Docker image with specific version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}

      - name: Tag Docker image with latest version
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image with latest version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy-job:
    runs-on: ubuntu-latest
    needs: build-and-push-job
    steps: 

      - name: Connect to the VPS using SSH.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}

          script: |
            cd /home/ubuntu/devops-ecommerce/api
            sudo git pull
            sudo docker compose pull
            sudo docker compose up -d --force-recreate --remove-orphans
