name:  CI/CD api-ecommerce

env:
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: api-ecommerce-image

on:
  push:
    branches:
      - main

jobs:

  build-and-push-job:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Source Code 
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Tag docker image with specific version
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
      
      - name: Push docker image with specific version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}


      - name: Tag docker image with latest version
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}::latest

      - name: Push docker image with latest version
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}::latest
    